[package]
name = "logjet"
version = "0.4.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
members = [".", "logjetd", "demo", "ljx", "liblogjet", "plugins/syslog-ingest"]
default-members = [".", "logjetd", "demo", "ljx", "liblogjet", "plugins/syslog-ingest"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
opt-level = "z"
incremental = false

[dependencies]
crc32c = "0.6"
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
zstd = { version = "0.13", default-features = false }

[dev-dependencies]
opentelemetry-proto = { version = "0.28", features = ["gen-tonic", "logs"] }
prost = "0.13"
