[package]
name = "logjet"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
members = ["logjetd", "demo"]
default-members = [".", "logjetd", "demo"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
opt-level = "z"
incremental = false

[dependencies]
crc32c = "0.6"
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
