[package]
name = "ljd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive", "wrap_help"] }
colored = "3"
libc = "0.2"
libloading = "0.8"
logjet = { path = ".." }
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
opentelemetry-proto = { version = "0.31", features = ["gen-tonic", "logs"] }
prost = "0.14"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pemfile = "2"
tiny_http = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.14", features = ["transport", "tls-ring"] }

[dev-dependencies]
rcgen = "0.12"
