[package]
name = "ljd"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
logjet = { path = ".." }
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
opentelemetry-proto = { version = "0.28", features = ["gen-tonic", "logs"] }
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-pemfile = "2"
tiny_http = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.12", features = ["transport", "tls"] }
