output: file
file.path: ./logs
file.size: 10
file.name: bofh.logjet
ingest.protocol: otlp-grpc
ingest.listen: 127.0.0.1:4317
replay.listen: 127.0.0.1:7002
collector.url: http://127.0.0.1:4318/v1/logs
collector.timeout-ms: 10000
