[package]
name = "liblogjet"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
opentelemetry-proto = { version = "0.28", features = ["gen-tonic", "logs"] }
prost = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
tonic = { version = "0.12", features = ["transport"] }
