output: file
file.path: ./logs
file.size: 5mb
file.name: stress.logjet
ingest.protocol: plugin
ingest.plugin-path: ../../target/debug/liblj_stress_ingest.so
ingest.listen: 127.0.0.1:7001
replay.listen: 127.0.0.1:7002
