name: Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Cache Rust build state
        uses: Swatinem/rust-cache@v2

      - name: Run unit tests
        run: make test-unit
